# Generated by Django 3.1.3 on 2020-11-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready')], default='PROCESSING', max_length=10)),
                ('file', models.FileField(upload_to='data_sets/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('FULL_NAME', 'Full Name'), ('JOB', 'Job'), ('EMAIL', 'Email'), ('DOMAIN_NAME', 'Domain Name'), ('PHONE_NUMBER', 'Phone Number'), ('COMPANY_NAME', 'Company Name'), ('INTEGER', 'Integer'), ('ADDRESS', 'Address'), ('DATE', 'Date')], max_length=12)),
                ('order', models.PositiveIntegerField()),
                ('start_from', models.IntegerField()),
                ('to', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.schema')),
            ],
        ),
    ]
