# Generated by Django 3.1.3 on 2020-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20201111_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_sets/'),
        ),
    ]
